
@base_url = http://127.0.0.1:8000



### Rest Framework Obtain Token
# @name token
POST {{base_url}}/api-token-auth/ HTTP/1.1
Content-Type: application/json

{
    "username": "support@gmail.com",
    "password": "squash"
}


### Rest Framework Test Authentication Required View
GET {{base_url}}/json/ HTTP/1.1
Content-Type: application/json
Authorization: Token {{token.response.body.token}}


### Rest Auth Registration
POST {{base_url}}/dj-rest-auth/registration/ HTTP/1.1
Content-Type: application/json

{
    "email": "agent@gmail.com",
    "password1": "squash",
    "password2": "squash"
}


### Rest Auth Login
# @name restAuthToken
POST {{base_url}}/dj-rest-auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "agent@gmail.com",
    "password": "squash"
}


### Rest Auth Test Authentication
GET {{base_url}}/json/ HTTP/1.1
Content-Type: application/json
Authorization: Token {{restAuthToken.response.body.key}}


### Creating a JWT
# @name jwt
POST {{base_url}}/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "nwokoronkem@gmail.com",
    "password": "squash"
}


### Refreshing a jwt
POST {{base_url}}/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{jwt.response.body.refresh}}"
}


### Testing jwt Authentication
GET {{base_url}}/json/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt.response.body.access}}



